### ISSUE TITLE
Custom functions registration system

### ISSUE THREAD

**Issue by ebryn** [prototypal-io/prius#14]
It should be possible to register custom functions for usage in Prius. The API I have in mind right now is similar to Handlebars:

```
Prius.register('color', function(values) {
  // ...
});
```

@mmun probably has thoughts about requirements but let's focus on a simple MVP for now.

**Comment by JFickel** [comment]
https://github.com/prototypal-io/prius/compare/packaging...register 

:blush:

**Comment by ebryn** [comment]
Implemented in 84cad0ad62deaf33af59d0a4a7da7f42859f5fed
